apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmGlobals:
  chartHome: ../charts

helmCharts:
  - name: prom-vehicle-exporter
    releaseName: prom-vehicle-exporter
    valuesFile: values.yaml
    namespace: apts-racev
