{{- range .Values.targets }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $.Release.Name }}-{{ .name | kebabcase }}
  namespace: {{ $.Release.Namespace }}
  labels:
    app.maxwin/group: {{ .name | kebabcase }}
    {{- with $.Values.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.maxwin/group: {{ .name | kebabcase }}
      {{- with $.Values.labels }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
  template:
    metadata:
      labels:
        app.maxwin/group: {{ .name | kebabcase }}
        {{- with $.Values.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      containers:
        - name: app
          image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag }}"
          imagePullPolicy: {{ $.Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ $.Release.Name }}-cm
          env:
          {{- range $key, $value := .env }}
            - name: {{ $key }}
              value: {{ quote $value }}
          {{- end }}
          {{- with .resources | default $.Values.resources}}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - containerPort: {{ $.Values.image.containerPort }}
              name: http
              protocol: TCP
---
{{- end }}
