{{- range $i, $e := until (int $.Values.groupCount) }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $.Release.Name }}-group-{{ $i }}
  namespace: {{ $.Release.Namespace }}
  labels:
    app.maxwin/group: group-{{ $i }}
    {{- with $.Values.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  replicas: {{ $.Values.replicaCount }}
  selector:
    matchLabels:
      app.maxwin/group: group-{{ $i }}
      {{- with $.Values.labels }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
  template:
    metadata:
      labels:
        app.maxwin/group: group-{{ $i }}
        {{- with $.Values.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      containers:
        - name: app
          image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag }}"
          imagePullPolicy: {{ $.Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ $.Release.Name }}-cm
          env:
            - name: VIN_GROUP_INDEX
              value: {{ quote $i }}
          {{- with $.Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - containerPort: {{ $.Values.image.containerPort }}
              name: http
              protocol: TCP
---
{{- end }}
