{{- range $i, $e := until (int $.Values.groupCount) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Release.Name }}-svc-group-{{ $i }}
  namespace: {{ $.Release.Namespace }}
  labels:
    app.maxwin/group: group-{{ $i }}
    {{- with $.Values.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ $.Values.service.type | default "ClusterIP" }}
  ports:
    - name: http-metrics
      port: {{ $.Values.service.port }}
      targetPort: http
  selector:
    app.maxwin/group: group-{{ $i }}
    {{- with $.Values.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
---
{{- end }}
