{{- range .Values.targets }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Release.Name }}-svc-{{ .name | kebabcase }}
  namespace: {{ $.Release.Namespace }}
  labels:
    app.maxwin/group: {{ .name | kebabcase }}
    {{- with $.Values.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ $.Values.service.type | default "ClusterIP" }}
  ports:
    - name: http-metrics
      port: {{ $.Values.service.port }}
      targetPort: http
  selector:
    app.maxwin/group: {{ .name | kebabcase }}
    {{- with $.Values.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
---
{{- end }}
