apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: keycloak

resources:
  - deployment.yaml
  - service.yaml

configMapGenerator:
  - name: keycloak-cm
    envs:
      - ".env.example"

secretGenerator:
  - name: keycloak-secret
    envs:
      - ".secret.env.example"

generatorOptions:
  disableNameSuffixHash: true

commonLabels:
  app.maxwin/name: keycloak
  app.maxwin/component: backend