apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: keycloak

resources:
  - ../bases

configMapGenerator:
  - name: keycloak-cm
    behavior: merge
    envs:
      - ".env"

secretGenerator:
  - name: keycloak-secret
    behavior: merge
    envs:
      - ".secret.env"

generatorOptions:
  disableNameSuffixHash: true

commonLabels:
  app.maxwin/name: keycloak
  app.maxwin/component: backend